In [24]:
import pandas as pd
import numpy as np
import statistics
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib as mpl
from tqdm.notebook import tqdm
import datetime
%matplotlib inline
plt.style.use('ggplot') # 그래프에서 격자로 숫자 범위가 눈에 잘 띄도록 ggplot 스타일을 사용
plt.rcParams['font.family'] = 'Malgun Gothic'

In [ ]:
# 나눔고딕코드 폰트 설치 (필요한사람만 돌리세요)
# !sudo apt-get install -y fonts-nanum
# !sudo fc-cache -fv
# !rm ~/.cache/matplotlib -rf
# plt.rc('font', family='NanumBarunGothic')

In [28]:
if 'google.colab' in str(get_ipython()):
    print('Running on CoLab')
    from google.colab import drive
    drive.mount('/content/drive')
    df = pd.read_excel('/content/drive/My Drive/빅데이터_콘테스트/base_line.xlsx', header=2)
else:
    print('Not running on CoLab')
    df = pd.read_excel('c:/bc/base_line2.xlsx', header=0)

Not running on CoLab

In [29]:
df

,NS Shop+ 2019.01.01~12.31,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,방송일시,노출(분),마더코드,상품코드,상품명,상품군,판매단가,취급액
1,2019-01-01 06:00:00,20,100346,201072,테이트 남성 셀린니트3종,의류,39900,2099000
2,2019-01-01 06:00:00,NaN,100346,201079,테이트 여성 셀린니트3종,의류,39900,4371000
3,2019-01-01 06:20:00,20,100346,201072,테이트 남성 셀린니트3종,의류,39900,3262000
4,2019-01-01 06:20:00,NaN,100346,201079,테이트 여성 셀린니트3종,의류,39900,6955000
...,...,...,...,...,...,...,...,...
38305,2020-01-01 00:20:00,20,100073,200196,삼성화재 행복한파트너 주택화재보험(1912),무형,0,NaN
38306,2020-01-01 00:40:00,20,100073,200196,삼성화재 행복한파트너 주택화재보험(1912),무형,0,NaN
38307,2020-01-01 01:00:00,20,100073,200196,삼성화재 행복한파트너 주택화재보험(1912),무형,0,NaN
38308,2020-01-01 01:20:00,20,100490,201478,더케이 예다함 상조서비스(티포트),무형,0,NaN
38309,2020-01-01 01:40:00,17.1667,100490,201478,더케이 예다함 상조서비스(티포트),무형,0,NaN

In [25]:
df['DAY'] = df['방송일시'].datetime.hour

KeyError: '방송일시'

In [22]:
idx_dict = {'start':0, 'end':0}
idx = 0
for row in tqdm(range(df.shape[0]-1)):
    current_day = df.loc[row]['DAY']
    next_day = df.loc[row+1]['DAY']
    current_group = df.loc[row+1]['p_group']
    next_group = df.loc[row+1]['p_group']
    current_mcode = df.loc[row]['m_code']
    next_mcode = df.loc[row+1]['m_code']
    if ((current_day == next_day) and abs(current_mcode - next_mcode) < 5 and (current_group == next_group)):
        pass
    else:
        idx_dict['end'] = row + 1
        df['code'][idx_dict['start']:idx_dict['end']] = idx
        idx += 1
        idx_dict['start'] = idx_dict['end']
#         print(row, idx)
#         print(idx_dict['start'],idx_dict['end'])
idx_dict['end'] = row + 2
df['code'][idx_dict['start']:idx_dict['end']] = idx

HBox(children=(FloatProgress(value=0.0, max=35378.0), HTML(value='')))

C:\Users\user\anaconda3\envs\mulcam\lib\site-packages\ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\user\anaconda3\envs\mulcam\lib\site-packages\ipykernel_launcher.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [21]:
df

,broadcast,exp_min,m_code,p_code,p_name,p_group,unit_price,total_price,sales,YEAR,MONTH,DAY,HOUR,MINUTE,SECOND,YEAR_DAY,DAY_NAME,DAY_NUM,code,no
0,2019-01-01 06:00:00,20.0,100346,201072,테이트 남성 셀린니트3종,의류,39900,2099000,53,2019,1,1,6,0,0,2019-01-01,Tuesday,2,0,0
1,2019-01-01 06:00:00,NaN,100346,201079,테이트 여성 셀린니트3종,의류,39900,4371000,110,2019,1,1,6,0,0,2019-01-01,Tuesday,2,0,1
2,2019-01-01 06:20:00,20.0,100346,201072,테이트 남성 셀린니트3종,의류,39900,3262000,82,2019,1,1,6,20,0,2019-01-01,Tuesday,2,0,2
3,2019-01-01 06:20:00,NaN,100346,201079,테이트 여성 셀린니트3종,의류,39900,6955000,174,2019,1,1,6,20,0,2019-01-01,Tuesday,2,0,3
4,2019-01-01 06:40:00,20.0,100346,201072,테이트 남성 셀린니트3종,의류,39900,6672000,167,2019,1,1,6,40,0,2019-01-01,Tuesday,2,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35374,2019-12-31 23:40:00,NaN,100448,201391,일시불쿠첸압력밥솥 6인용,주방,148000,10157000,69,2019,12,31,23,40,0,2019-12-31,Tuesday,2,6858,35374
35375,2019-12-31 00:00:00,20.0,100448,201383,무이자쿠첸압력밥솥 10인용,주방,178000,50929000,286,2019,12,31,0,0,0,2019-12-31,Tuesday,2,6858,35375
35376,2019-12-31 00:00:00,NaN,100448,201390,일시불쿠첸압력밥솥 10인용,주방,168000,104392000,621,2019,12,31,0,0,0,2019-12-31,Tuesday,2,6858,35376
35377,2019-12-31 00:00:00,NaN,100448,201384,무이자쿠첸압력밥솥 6인용,주방,158000,13765000,87,2019,12,31,0,0,0,2019-12-31,Tuesday,2,6858,35377
35378,2019-12-31 00:00:00,NaN,100448,201391,일시불쿠첸압력밥솥 6인용,주방,148000,46608000,315,2019,12,31,0,0,0,2019-12-31,Tuesday,2,6858,35378