In [3]:
import pandas as pd
import numpy as np
import statistics
import matplotlib.pyplot as plt
import seaborn as sns
import datetime

In [5]:
if 'google.colab' in str(get_ipython()):
    print('Running on CoLab')
    from google.colab import drive
    drive.mount('/content/drive')
    rate = pd.read_excel('/content/drive/My Drive/빅데이터_콘테스트/data_information/bigcontest_rate_train.xlsx', header=1, index_col = '시간대', skipfooter=1).drop(columns='2019-01-01 to 2019-12-31')
else:
    print('Not running on CoLab')
    rate = pd.read_excel('c:/bc/bigcontest_rate_train.xlsx', header=1, index_col = '시간대', skipfooter=1).drop(columns='2019-01-01 to 2019-12-31')

Not running on CoLab

In [6]:
rate

,2019-01-01,2019-01-02,2019-01-03,2019-01-04,2019-01-05,2019-01-06,2019-01-07,2019-01-08,2019-01-09,2019-01-10,...,2019-12-22,2019-12-23,2019-12-24,2019-12-25,2019-12-26,2019-12-27,2019-12-28,2019-12-29,2019-12-30,2019-12-31
시간대,,,,,,,,,,,,,,,,,,,,,
02:00,0.0,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.000,0.000,...,0.0,0.000,0.000,0.000,0.0,0.000,0.0,0.0,0.000,0.000
02:01,0.0,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.000,0.005,...,0.0,0.000,0.000,0.000,0.0,0.000,0.0,0.0,0.000,0.012
02:02,0.0,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.000,0.005,...,0.0,0.000,0.000,0.000,0.0,0.000,0.0,0.0,0.000,0.000
02:03,0.0,0.0,0.014,0.0,0.000,0.0,0.0,0.0,0.000,0.005,...,0.0,0.000,0.000,0.017,0.0,0.000,0.0,0.0,0.000,0.000
02:04,0.0,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.000,0.005,...,0.0,0.000,0.000,0.017,0.0,0.000,0.0,0.0,0.000,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
01:55,0.0,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.004,0.000,...,0.0,0.013,0.000,0.000,0.0,0.015,0.0,0.0,0.000,0.000
01:56,0.0,0.0,0.000,0.0,0.027,0.0,0.0,0.0,0.000,0.000,...,0.0,0.013,0.000,0.000,0.0,0.015,0.0,0.0,0.000,0.000
01:57,0.0,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.004,0.000,...,0.0,0.013,0.000,0.000,0.0,0.015,0.0,0.0,0.000,0.000
01:58,0.0,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.004,0.000,...,0.0,0.013,0.017,0.000,0.0,0.015,0.0,0.0,0.019,0.000
01:59,0.0,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.004,0.000,...,0.0,0.013,0.000,0.000,0.0,0.015,0.0,0.0,0.000,0.000

In [20]:
# 분 단위 데이터 시간 단위로 변환 후 데이터프레임으로 리턴
temp = []
def integrate_rate(data, unit=60, operation = 'sum'):
    n_rows = int(len(data.index) / unit) # -> 24

    column_names = data.columns
    index_names =  np.arange(0,24,1)+2
    range_ = np.arange(0,1440,60)

    if operation == 'sum':  
        for _, j in enumerate(range_):
            temp.append(data[j:j+unit].sum(axis=0))

        data_array = np.array(temp)

        return pd.DataFrame(data=data_array, index = index_names, columns = column_names)[4:]

  # elif operation == 'mode':
  #   for j in range_:
  #     data[j:j+unit].sum(axis=0)

In [23]:
rate2 = rate.T
rate2

시간대,02:00,02:01,02:02,02:03,02:04,02:05,02:06,02:07,02:08,02:09,...,01:50,01:51,01:52,01:53,01:54,01:55,01:56,01:57,01:58,01:59
2019-01-01,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.014,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
2019-01-02,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
2019-01-03,0.0,0.000,0.0,0.014,0.0,0.0,0.0,0.0,0.0,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
2019-01-04,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
2019-01-05,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.027,0.000,0.000,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2019-12-27,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.000,...,0.015,0.015,0.015,0.015,0.015,0.015,0.015,0.015,0.015,0.015
2019-12-28,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
2019-12-29,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
2019-12-30,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.019,0.000
2019-12-31,0.0,0.012,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000

In [25]:
def rate_interval()
    rate2.loc['2019-01-01','02:00':'02:10']

시간대
02:00    0.000
02:01    0.000
02:02    0.000
02:03    0.000
02:04    0.000
02:05    0.000
02:06    0.000
02:07    0.000
02:08    0.000
02:09    0.014
02:10    0.000
Name: 2019-01-01, dtype: float64